[package]
name = "r-x86-64"
version = "0.1.0"
authors = ["rchaser53 <tayoshizawa29@gmail.com>"]
edition = "2018"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.17.1"

[dependencies]
lalrpop-util = "0.17.1"
regex = "1.2.1"
nom = "5.0.0"
